name: CD Pipeline


on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name:  Pull Docker image
      run: sudo docker pull rishisiva03/raggenai:latest

    - name:  Stop and remove existing container
      run: |
        sudo docker stop backend_api || true
        sudo docker rm backend_api || true

    - name:  Run Docker container
      run: sudo docker run -d -p 8000:8000 --name backend_api rishisiva03/raggenai:latest